name: 01 Basic
on:
  push
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: Step2
        run: echo "Hello World 2"
